name: Sample Run Include Syntax
on: push
env: 
  matrixConfig: {"run":["run1","run2"]}
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(env.matrixConfig)}}
        run: ['run1', 'run2']
        include:
          - run: 'run3'

    steps:
    - run: echo Run ${{ matrix.run }}
    - run: date
    - run: sleep 1
    - run: date